version: '3'

services:
  dup_exporter:
    image: mrflobow/duplicati_exporter:0.1
    container_name: dup_exporter
    networks:
      - mynetwork
    ports:
      - "9123:9123"
    restart: unless-stopped
networks:
  mynetwork:
    external: true